// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx0PoZjxdPBO_GJdfF-OvPDf1xliSdUh0',
    appId: '1:728473283818:web:87a74055f5d28fba98bb93',
    messagingSenderId: '728473283818',
    projectId: 'drivemate-a0355',
    authDomain: 'drivemate-a0355.firebaseapp.com',
    storageBucket: 'drivemate-a0355.firebasestorage.app',
    measurementId: 'G-3SZ6W296C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp5T1wdgVfeKeVp9gb_Zg0kJvvActrd4c',
    appId: '1:728473283818:android:620ea804e05a081a98bb93',
    messagingSenderId: '728473283818',
    projectId: 'drivemate-a0355',
    storageBucket: 'drivemate-a0355.firebasestorage.app',
  );
}
